version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 3000:3000
    working_dir: /app-frontend
    links:
      - backend
    depends_on:
      - backend
    volumes:
      - ./front-end:/app-frontend
    restart: 'always'

  backend:
    container_name: app_backend
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./back-end/src:/app-backend/src
    links:
      - db
    depends_on:
      - db
    environment:
      APP_PORT: 3001
      JWT_SECRET: jwt_secret
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
      MYSQL_PORT: 3306
    restart: 'always'
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: 'always'
